name: Run Jupyter Notebook

on:
  push:
    branches:
      - main

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jupyter nbconvert

    - name: Execute notebook
      run: |
        jupyter nbconvert --to notebook --execute sachitGame.ipynb --output executed_/sachitGame.ipynb

    - name: Upload executed notebook as artifact
      uses: actions/upload-artifact@v3
      with:
        name: executed-notebook
        path: executed_notebook.ipynb
